### ISSUE TITLE
DAMS UI - display File 2 for all file types

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#165]
### Descriptive summary

Display the file 2 (source files) download button for all components that have them.

### Rationale

Currently, file 2 (usually a zip of raw source files) does not display in the component viewer for audio or video files as it does for still image and documents.  Data providers and the digital archivist have requested this as a way to ingest raw source files, ISO disc images, and accompanying metadata to a simple objects or any component of a complex object.  These files can be ingested currently, but they are not visible in the UI.

### Expected behavior

When in curator mode, display download button for linked *-source file for all objects and components.

Desired results for audio and video files:
![image](https://user-images.githubusercontent.com/5453716/28842623-379f81f8-76b3-11e7-97c5-5dd4b29ef634.png)

![image](https://user-images.githubusercontent.com/5453716/28842714-889d399c-76b3-11e7-82aa-be6964ebeb6e.png)

**Comment by arwenhutt** [comment]
Thanks @GregReser  I think this is a good feature request that we'll want to consider for DAMS 5.  There may be a bit more spec work needed once we have the file-use behaviors locked down, since presumably there are some different possible interactions between the two file 1 and file 2 depending on the file-use values.  

@gamontoya I'm wondering if we have a place/label for D5 requests?  Even before going to products, I think we'd want to review again once D5 is up and running (in some capacity) - to make sure it's not something that Hyrax already has (which seems unlikely in most cases, but possible), and to have a clearer idea of what implementation would entail.

**Comment by lsitu** [comment]
@arwenhutt @gamontoya I think the feature is implemented in DAMS 5 already:
<img width="1298" alt="screen shot 2017-08-02 at 12 51 49 pm" src="https://user-images.githubusercontent.com/2430784/28892357-8f1262a0-7782-11e7-8655-b68e2b53d4af.png">

**Comment by gamontoya** [comment]
@GregReser @arwenhutt This really should be a DAMSPAS ticket, but I'll leave this here since there is commenting happening already.

**Comment by gamontoya** [comment]
Revisit with Hyrax.
