### ISSUE TITLE
Authority report on a list of arks

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#171]
### Descriptive summary
We need a report on the authority records created since the reports from 2016.  We've been tracking records created via the subject import tool and I've included the list of arks.  

### Details
Using the list of authority record arks attached, please run a report which includes:
1. DAMS_ARK (provided)
2. AuthoritativeLabel
3. Predicate
4. ExactExternalAuthority (when present)
5. Sample Object	
6. Object Counts

This is the same report as we've asked for before, the differences being:
- we are providing a list of authority arks
- the addition of the value in the <mads:hasExactExternalAuthority> (#4 above)

[new subject arks 9-1.txt](https://github.com/ucsdlib/damsmanager/files/1279395/new.subject.arks.9-1.txt)

**Comment by lsitu** [comment]
@arwenhutt Where can I find the arks of the authority records that you want for the report?

**Comment by arwenhutt** [comment]
@lsitu doh! I forgot to attach the list, sorry - adding now.

**Comment by lsitu** [comment]
Got it. Thanks Arwen.

**Comment by lsitu** [comment]
@arwenhutt Here is the report for the subjects with those ARKs provided above. I just added in an additional column "Subject Type" to the report so that we can compare it with the predicates used in DAMS. Please let me know if you want to remove it. Thanks.
[Subjects-report.txt](https://github.com/ucsdlib/damsmanager/files/1283016/Subjects-report.txt)

**Comment by arwenhutt** [comment]
@lsitu looks great, thanks!
