### ISSUE TITLE
METS/MODS to CSV not importing subjects

### ISSUE THREAD

**Issue by GregReser** [ucsdlib/damsmanager#241]
### Descriptive summary
DAMS Manager MARC/MODS Import tool, CSV preview is not converting subjects (they do not appear at all in the CSV output file)
 - mods:subject
   - mods:name
   - mods:topic
### Expected behavior
Subjects should be exported to appropriate DAMS ingest template columns

### Actual behavior
Subjects are not exported

### Steps to reproduce the behavior
 METS/MODS test records attached with CSV output
[MetsMods_test.zip](https://github.com/ucsdlib/damsmanager/files/2271197/MetsMods_test.zip)
[preview-445050521.txt](https://github.com/ucsdlib/damsmanager/files/2271200/preview-445050521.txt)

### Dependent work
AV Dissertation ingest https://lib-jira.ucsd.edu:8443/browse/DI-41

**Comment by GregReser** [comment]
@gamontoya I can't work on the AV Diss ingest until this is resolved

**Comment by GregReser** [comment]
Subjects used to work in the METS/MODS transform.  It was discussed in the original ticket. https://lib-jira.ucsd.edu:8443/browse/DM-33

Maybe this changed when we moved to CSV output https://github.com/ucsdlib/damsmanager/issues/116
Perhaps we used an older stylesheet?

**Comment by lsitu** [comment]
@GregReser I tried http://roger.ucsd.edu/record=b8529446~S9 and I got 7 Subject:topic and 1 Person:author: 
[preview-530079460.csv.txt](https://github.com/ucsdlib/damsmanager/files/2275086/preview-530079460.csv.txt)
So I think the mapping is the same in CSV except those mappings that were requested for changes. I think we haven't mapped all MARC/MODS fields to the MARC/MODS Import tool. Could you give me more information regarding what MARC fields are missing and how could those fields be mapped to CSV so that we can do it specifically?

**Comment by GregReser** [comment]
@lsitu This is for the METS/MOD to CSV, not MARC.  Try the METS/MODS file I attached above (MetsMods_test.zip)

**Comment by lsitu** [comment]
@GregReser I see. I think we haven't touch that METS/MODS conversion part for a long time. I just did a test to convert the example b3595145x-metsmods.xml from METS/MODS to dams4 RDF/XML format that we got for preview before moving to the CSV output. But I don't see any subjects showing up in the dams4 RDF/XML preview format. So I think it might not related to moving to the CSV output but the METS/MODS to dams4 RDF/XML conversion itself:
[preview_b3595145x-rdf.xml.txt](https://github.com/ucsdlib/damsmanager/files/2283994/preview_b3595145x-rdf.xml.txt)

It's strange that the subjects are missing from the METS/MODS source since both MARC and METS/MODS conversions are sharing the same codes and the same stylesheet for subjects conversion. Do you see all other mods elements and the component structures are converted as expected or not?

**Comment by lsitu** [comment]
@GregReser Now I found we've changed it not to include those non-FAST subject headings since we introduce FAST headings in MARC conversions: https://github.com/ucsdlib/damsmanager/issues/104

Do you want to do it differently for METS/MODS to include any subjects that are not "FAST" headings?

**Comment by GregReser** [comment]
@lsitu Yes please.  Any subjects for METS/MODS.  Actually, we have been thinking of changing the MARC to CSV to also include any subject.  Would that be an easy change to make for both METS/MODS and MARC to CSV at the same time?  Maybe we can solve two things at once here.  Let me know if they are separate and need separate tickets.

**Comment by lsitu** [comment]
@GregReser Sure. I don't think we need another ticket and this could be handled in the same stylesheet.
@gamontoya Is the ticket ready?

**Comment by GregReser** [comment]
@lsitu Great.  One request: when FAST subjects are exported, could the column header indicate that. e.g., "Subject:topic FAST"?  These will not be valid column headers and that is OK.  We will use these to identify subjects for reconciliation as we are preparing the ingest spreadsheet.

**Comment by lsitu** [comment]
@GregReser I think we may not be able to do it since the CSV output is converted from the DAMS4 RDF/XML, which doesn't have the corresponding property for "FAST" headings but the general mads:hasExactExternalAuthority property.
Do you want to use a header like "Subject:topic FAST" for all those subjects that contains mads:hasExactExternalAuthority instead?

**Comment by lsitu** [comment]
@GregReser Yep, I think that could be something that we can manipulate for.

**Comment by GregReser** [comment]
@lsitu That's great, thanks.

**Comment by GregReser** [comment]
@lsitu just to clarify, The FAST subjects should still be broken out to specific columns by type, they will just have "FAST" added to the column header.  So, "Subject:topic FAST", "Subject:personal name FAST", etc.

**Comment by lsitu** [comment]
@GregReser Sure. Will the columns with "FAST" for fast headings apply to MARC to CSV conversion or not?

**Comment by lsitu** [comment]
@GregReser Since in ticket https://github.com/ucsdlib/damsmanager/issues/104 we decided not to extract those non-FAST headings subjects, I think we can start with not to display "FAST" in the subject columns for the MARC to CSV tool. What do you think?

**Comment by GregReser** [comment]
@lsitu correct, this would be a change from the decision in #104.  We want to change to extract both FAST and non-FAST subjects now and if they are FAST place them in separate columns and add " FAST" to the column header.
This will be for MARC to CSV tool.  I don't think we will encounter FAST in METS/MODS, but maybe it is all combined into one conversion process, which is fine.  Basically, we want all subjects and we want to know which ones are FAST

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/242 to support METS/MODS to CSV and MARC to CSV with FAST headings basing on the discussions with @GregReser above. It's ready for review now. Thanks.
