### ISSUE TITLE
Create report (output) for all RDCP collections

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damsmanager#253]
### Descriptive summary

For the figshare project, Ho Jung needs a report containing the following information:

- Collection title
    - Collection URL
- Object title
    - Object URL
- DOI in Preferred Citation (or whole citation, if DOI alone is difficult to parse)
- Number of components in object (for objects only)

### Deliverable 

- CSV output (or Excel)

**Comment by lsitu** [comment]
@gamontoya Do you want to have all RDCP collections and objects in one CSV file, or separate them collection by collection? For counting `Number of components in object`, do we need to count those nested components (components inside a component) or not?

**Comment by gamontoya** [comment]
@hjsyoo Can you please answer Longshou's questions above?

**Comment by hjsyoo** [comment]
Hi @lsitu, I'd like to have one CSV file with all collections and objects listed, where there's a column for each of the variables listed in the Description above. For number of components, I just need a total number of components, whether they're parent or child components. But one other variable that would be useful is the number of files associated with the object. So for example, this object, https://library.ucsd.edu/dc/object/bb0820653z, has 13 total components, but only 10 files. Can we get file counts as well, in the report?

**Comment by lsitu** [comment]
@hjsyoo Yes, I think we can count the files in each object as well. How about adding a column name like `Number of files` for it? Do you want to count any alternate files, like image-alternate, audio-alternate etc.?
With reporting collections and objects in one single CSV file, how about list the collections one by one with listing the collection CLR first and then the objects in that collection? I think we can add an empty line for each collection. Do you want to leave the `Collection title` field and the `Collection URL` field empty for the objects in this case?

**Comment by hjsyoo** [comment]
@lsitu Yes, a column name, NumberOfFiles would be great. I don't need alternate files. There should be one row for each object, and the CollectionTitle and CollectionURL should not be empty - please do include that information, even though it's repeated for every object in the collection. I believe with this format, the only column that may have empty cells will be the DOI (many objects do not have one). All other columns should be completely filled. Let me know if you have other questions. Thanks!

**Comment by lsitu** [comment]
@hjsyoo Thanks. That sounds good.

**Comment by lsitu** [comment]
@gamontoya / @hjsyoo Here is the report with the additional column `Number of Files` added, which has all RDCP collection CLRs and the objects in one CSV file:
[Report-RDCP.csv.txt](https://github.com/ucsdlib/damsmanager/files/2389838/Report-RDCP.csv.txt)

I rename the csv file to .txt so that I can attach it here and you can simply rename it to `Report-RDCP.csv` to open it with Excel. It looks like that the DOI has different formats like `http://doi.org/`, `https://doi.org/`, `http://dx.doi.org/` etc. And most of the DOIs were appended to the end of the preferred citation note, while some were inserted inside the note text, and some were embedded links instead of plain text. I also found several of the preferred citation notes in dataMares collection contain no DOI, and I've included the whole note in this case for your reference. Please let me know if you want any changes.

**Comment by hjsyoo** [comment]
@lsitu The report is exactly what I need. Thanks!
