### ISSUE TITLE
Decouple/simplify rights and access controls

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#264]
### Descriptive summary
Currently some rights information is used to determine access levels.  This leads to more complexity and less predictable behavior.  We would like to decouple access from rights. 

### Rationale
Simplify implementation so it is more understandable and predictable, easier to code, and easier to assign metadata for.

### Related work
https://github.com/ucsdlib/damspas/issues/541

**Comment by GregReser** [comment]
### Sample use case:
We would like to create objects that are limited to UCSD only and are not discovered through a search, but can be accessed directly by using the https ARK. This should be possible by using a localDisplay and suppressDiscovery overrides. 

Currently, this only works if copyright status is public domain and there is no Rights Holder.  If there is a Rights Holder, the object is found through a search (on campus the file is displayed, off campus, it is metadata-only).  The cause seems to be the existence of a license/permission = localDisplay.  Without a license/permission localDisplay, an object with a rights holder is not accessible by any method (search or https ARK).

Also, it should be possible to control the ability to download files independently of the localDisplay and suppressDiscovery overrides.  Currently, these overrides allow file download, which will not meet the requirements for all objects.

**Comment by lsitu** [comment]
@GregReser It seems like we need to separate the license and access override here. With the current values from the Excel Ingest form, we'll have:

**- License**
1. Public - granted by rights holder (public access granted by rights holder)
2. UCSD - granted by rights holder (localDisplay)
3. Restricted - by rights holder (Display currently prohibited)
4. Creative Commons - Attribution (http://creativecommons.org/licenses/by/4.0/)
5. Creative Commons - Attribution-ShareAlike (http://creativecommons.org/licenses/by-sa/4.0/)
6. Creative Commons - Attribution-NoDerivs (http://creativecommons.org/licenses/by-nd/4.0/)
7. Creative Commons - Attribution-NonCommercial (http://creativecommons.org/licenses/by-nc/4.0/)
8. Creative Commons - Attribution-NonCommercial-ShareAlike (http://creativecommons.org/licenses/by-nc-sa/4.0/)
9. Creative Commons - Attribution-NonCommercial-NoDerivs (http://creativecommons.org/licenses/by-nc-nd/4.0/)

**- Access override**
1. Public - open fair use
2. Public - metadata only fair use
3. UCSD - educational fair use
4. Curator
5. Click through - cultural sensitivity
6. Restricted - cultural sensitivity
7. suppressDiscovery

**Note:** We haven't include the suppressDiscovery option in the form for the Excel InputStream tool yet. 

And the copyright status will be the same:
1. Public domain
2. Copyright UC Regents
3. Copyrighted (Person)
4. Copyrighted (Corporate)
5. Copyrighted (Other)
6. Unknown

Does it sound good to decouple/simplify rights and access control this way?

**Comment by GregReser** [comment]
@lsitu I think we will have to make additional changes to what metadata is created by the DAMS Manager selections and to the access control logic. 

In my Use Case 1 above, suppress discovery of a copyrighted object would still not work because I would specify "UCSD - granted by rights holder (localDisplay)" which would create a License/Permission which is overriding suppressDiscovery and allowing the object to be found in a search.  Currently, a personal or corporate copyrighted object must have a License to be displayed (except UC Regents which has it's own logic).

Maybe we could break that dependency and assume a copyrighted object can be displayed unless there is a restriction on it.  Also, handling UC Regents differently in the access logic which adds special rules and confusion.

This is a test object that should be suppressDiscovery but is still searchable: https://librarytest.ucsd.edu/dc/object/bd4014597t

**Comment by lsitu** [comment]
@GregReser Yes. I see that. We may need to adjust the access control logic a little bit in damsrepo when needed. So just list the fields/values that you want to have in the ingest form, along with the use cases for the expected access control behavior for a combination of the values that we want, and we can adjust the access control logic in damsrepo to make it works. Thanks.

**Comment by GregReser** [comment]
@lsitu just trying to confirm current access behavior to see what we might need to change...

It seems like a Note:note can control access and boilerplate display.  This test object, created with DAMS Manger Excel ingest, has no License or otherRights, it only has a Note:note that begins with the text "Culturally sensitive content:"  This note is causing this behavior:
https://librarytest.ucsd.edu/dc/object/bd7529991m
- From UCSD IP - object is not accessible
- From home (public) - object is accessible with click through boilerplate.  Boilerplate text is taken from the Note:note

Result from home:
![image](https://user-images.githubusercontent.com/5453716/49240301-bbcbe000-f3b9-11e8-9980-ee0c3b63f817.png)

**Comment by lsitu** [comment]
@GregReser Object https://librarytest.ucsd.edu/dc/object/bd7529991m is a curator-only object since it has no License or otherRights. And yes, the Note:note with "Culturally sensitive content:" will trigger the click through boilerplate.
In public, I don't think you can access the object it. And you may need to use an Incognico window to test it.

**Comment by GregReser** [comment]
OK, got it, thanks.

**Comment by GregReser** [comment]
@lsitu I understand now that metadata only (including cultural sensitivity) boilerplate text is hard coded, but cultural sensitivity click through boilerplate comes from Note:note.  Is this correct?

**Comment by lsitu** [comment]
@GregReser Yes. I think it's correct.

**Comment by GregReser** [comment]
@lsitu Here is my proposal to simplify the access/visibility controls.  This approach will require some changes to the display logic, but will use existing predicates and values in order to minimize large batch object edits.

The big changes to consider:
- Since local CLRs and objects are now public metadata only, there is no need to consider CLR visibility = local in the logic. The only test for CLR visibility will be for curator.  Suppressing an entire collection is still useful for QA before release.
- All copyright holders will be treated the same. We won't assume UC Regents objects have different access/visibility than other rights holders.  If an object needs to be restricted, it must contain a restriction value.
- License will not be required for person/corporate rights holder.  If there is no restriction, the object will be public.
- Suppress discovery is separated from local and public access for more flexibility.  If this will require a high LOE, we can reconsider this.

If this approach is acceptable, I will map out the expected predicates and values for each outcome.  We will be implementing this in the Excel ingest spreadsheet, not the DAMS Manager tool.

![image](https://user-images.githubusercontent.com/5453716/49390575-35c3d800-f6de-11e8-8072-171119284740.png)

**Comment by lsitu** [comment]
@GregReser I believe the change is big and it will affect both the access control logic and UI display, especially the UCSD IP/metadata-only features. And I am not sure how this change will affect the display behavior for those objects held by UC Regents.
Maybe we need a report for those objects held by UC Regents first? And also, with the changes above, I think we may need to rethink about the implementation of the UCSD IP/metadata-only features. What do you think?

**Comment by GregReser** [comment]
@lsitu I'm hoping we won't have to rethink the UCSD IP/metadata-only features too much.  I tested various DAMS Manager ingest access options to see what works and I think most things will not change.  I might be overlooking something, so we should look carefully at each scenario.  UC Regents would be a good place to start

For rights holder UC Regents
- Public UC Regents objects are easy - they have no License/OtherRights, so nothing should change
- Local Display UC Regents - weren't these objects recently changed to include OtherRights//dams:Permission/@type=metadataDisplay?  These were Kelco, Center for Music Experiment, Department of Music Concert Archive, etc.  I think they will behave correctly in the current logic, at least it seems that way in my tests.  It seems like it doesn't matter if the CLR is local or public, if the object has metadataDisplay, it displays that way to everyone.

Do you think it is possible we have some UC Regents with local CLR where the objects do not have metadataDisplay?

**Comment by lsitu** [comment]
@GregReser I think the issue is in the first change that you suggested above:
```
Since local CLRs and objects are now public metadata only, there is no need to consider CLR visibility = local in the logic. The only test for CLR visibility will be for curator. Suppressing an entire collection is still useful for QA before release.
```
`visibility = local ` is used to determine the UCSD IP/metadata-only display feature at this time.

For your question, `Do you think it is possible we have some UC Regents with local CLR where the objects do not have metadataDisplay?`, I don't know exactly. Maybe we need a report or do some search to find it out?

**Comment by lsitu** [comment]
@GregReser Yes. I think if we don't need it, then we may need to update the access control logic and damspas UI for the changewe need.

**Comment by GregReser** [comment]
@lsitu OK, I'll open a ticket to see what access values we have in local collections.

**Comment by gamontoya** [comment]
@GregReser Where are we with this ticket? Is it waiting for you?

**Comment by GregReser** [comment]
@gamontoya getting more info on metadata only policy

**Comment by lsitu** [comment]
@GregReser Do we have any decisions made for the ticket that I can move forward to work on? Thanks.

**Comment by GregReser** [comment]
@lsitu I'm putting together a summary of options for discussion.  I'll complete that when I return to work on 01/07.

**Comment by arwenhutt** [comment]
I'm going to close this ticket as I think it has served the purpose of initial discussion and getting the ball rolling on how we can approach this high level goal.  

Next steps will be tracked in the Decouple rights metadata from access controls (epic) #311 ticket
