### ISSUE TITLE
Address indexing queue wait time

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/damsmanager#266]
### Descriptive summary
Editing a CLR launches a re-index of all objects in the collection and all linked sub-collections, creating a very large queue which delays indexing of unrelated edits and ingests.  While some edits, such as Title value, do have an impact on all linked objects, many other edits do not and therefore should not trigger a full re-index.  

Long indexing queues, whether triggered by a CLR edit, or any other edit or ingest job, can have negative impacts on time sensitive changes to records (i.e. embargo content, correct erroneous information) DOMM is asked to make.  We would like to be able to push re-indexing of an item to the front of the queue.

### Request
- Determine which CLR edits necessitate a full re-index of all linked collections and objects.
- Determine if adding/removing CLR links to parent/child CLRs necessitates a full re-index of all linked collections and objects.
- Change DAMS Manager collection create/import, RDF edit, ingest tools to only re-index collections and objects when necessary.
- Create a tool to allow us to immediately re-index an item or items.

**Comment by gamontoya** [comment]
Per Longshou:

```Yes, I think we can add an option for not indexing those objects in a collection, but 
this may cause the inconsistent issue.

Maybe we can make the collection the `urgent` priority, while the objects in the 
collection are `high` priority. 

The `urgent` one is more important. I think we can add a checkbox `Urgent` in the 
RDF Import form to do the trick if the checkbox is checked.```

**Comment by lsitu** [comment]
@arwenhutt / @mcritchlow  I've added PR https://github.com/ucsdlib/damsmanager/pull/282 that will give the item edited the highest level of priority 9, and all other linked records will be indexed in a lower priority. I also update our dev tool to index single items in the highest priority so that we can index some urgent items at any time. The PR is ready for review now.

Attached is the screenshot of the optional checkbox on the bottom for urgent indexing in the RDF Edit tool:
 <img width="1039" alt="screen shot 2018-11-02 at 1 46 05 pm" src="https://user-images.githubusercontent.com/2430784/47941542-c626b700-deab-11e8-9580-9c248ce787c3.png">

Per my experience in the past, I think the item with highest priority should be index in around 20 minutes. Does it sound good to you?
