### ISSUE TITLE
Support batch export metadata in RDF and CSV format

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damsmanager#301]
### Descriptive summary

Batch export metadata in CSV and RDF format with an ARK list or objects in a collection.

### Rationale

To support Batch edit in https://github.com/ucsdlib/damsmanager/issues/263, we need to tool to export metadata in CSV format. The tool should be able to export metadata provided by a list of ARKs, or objects/ARKs in any collection(s).

### Related work

https://github.com/ucsdlib/damsmanager/issues/263

**Comment by gamontoya** [comment]
@lsitu Is this ticket done or are you waiting for a review of the work?

**Comment by arwenhutt** [comment]
@lsitu we've finished up the spec for batch export: https://docs.google.com/document/d/1NAEVvYkU4oqfrZTaSrjbPwUyIGd9meFkkOyzR8ZlO9c/edit?usp=sharing
You should be able to comment and add questions within the document but, let me know if you have any access issues.

**Comment by arwenhutt** [comment]
@lsitu We've also completed an initial review of the sample export file: 

_Unless otherwise noted review was done on xlsx file created by importing csv from within excel, using the “from text” function, with file origin encoding of Unicode/UTF8, comma delimiters, and manually setting column date formats for Begin Date and End Date to text._
1. Problem with incorrect new line for objects: http://library.ucsd.edu/ark:/20775/bb7511362r and http://library.ucsd.edu/ark:/20775/bb6793765b 
2. There are names output without roles - columns M-N have the header “Corporate: “ and AF-AI “Person: “ with no role following the colon. From looking at a few of the names in these columns in the rdf object records, some or perhaps all, of the names have associated roles.
    * E.g. in object http://library.ucsd.edu/ark:/20775/bb42690127 “López-Sagástegui, Catalina” (AF4) has a role of “research team head” so should be in column with a header of “Person:Research team head”
3. There’s lots of missing data in the export file, a few examples:
    * For the object: http://library.ucsd.edu/ark:/20775/bb35181500 a comparison of the exported metadata with the rdf record shows:
        * Three of the five names are missing
        * The four geographics are missing from the export
        * The one topic is missing 
    * There also appear to be missing files, partial/whole notes, etc.
4. There’s a column header “Subject:topic FAST” (BL) - this should just be Subject:topic

**Comment by lsitu** [comment]
@arwenhutt Thanks for the CSV review. I just added a couple of comments in the the spec for batch export.

**Comment by GregReser** [comment]
@lsitu a couple of bugs (I think)
1. The output is creating columns for properties that don't exist in the objects
Subtitle	Translation	Variant
2. The column "license:permission/type" is sometime repeated multiple times
 a. When exporting two collections at once (bb67932564, bb30391860) the column "license:permission/type" was repeated 54 times, all with the same value "display".  See attached file PNG.xlsx
b. The column "license:permission/type" was repeated 1370 times for collection bb08204951. See attached file Scheffler.xlsx
c. 
[PNG.xlsx](https://github.com/ucsdlib/damsmanager/files/3055794/PNG.xlsx)
[Scheffler.xlsx](https://github.com/ucsdlib/damsmanager/files/3055795/Scheffler.xlsx)

In both cases above, the dams:permission value is bb6110650g.  THat object looks OK, but maybe there is something wrong with it that is causing the repeat columns.

Not a bug exactly, but a change:

1. Do not add space \ to Component and Sub-component, since we are no longer using them in the template

**Comment by lsitu** [comment]
@GregReser We have the following required fields for MODS/MARC Import tool, which is sharing the same code template:
`Object Unique ID`
`Level`
`File name`
`File use`
`Type of Resource`
`Language`
`Title`
`Subtitle`
`Translation`
`Variant`

So the fields will show up no matter what. I would suggest use the same rule for both tools if possible. Would you like to remove field `Subtitle`, `Translation`, `Variant` from the required fields list for both MODS/MARC Import and Batch Export tool?

**Comment by GregReser** [comment]
@lsitu I don't recall ever having an error because I didn't include Subtitle, Translation, Variant.
I just did a test ingest using this spreadsheet and didn't get an error without those fields, so I don;t think they are required and they shouldn't be
[xls_standard_input_test.xlsx](https://github.com/ucsdlib/damsmanager/files/3056159/xls_standard_input_test.xlsx)

**Comment by lsitu** [comment]
@GregReser I think that's something we talked about in the past while adding support for MODS/MARC Import tool, in which we need those fields exported in Excel. Yes, it won't trigger any errors. But I need you to confirm whether we should remove `Subtitle`, `Translation`, and `Variant` fields from the MODS/MARC Import tool or not. Thanks.

**Comment by GregReser** [comment]
@lsitu Yes, you can remove `Subtitle`, `Translation`,` Variant` as required fields from the MODS/MARC Import tool.

**Comment by lsitu** [comment]
@mcritchlow I've added PR https://github.com/ucsdlib/damsmanager/pull/318 to address the issues that @GregReser raised. I'll deploy it to staging again for test once the PR is merged. Thanks.
