### ISSUE TITLE
Apply a conditional placement (RDC/non-RDC) for Note:Preferred Citation

### ISSUE THREAD

**Issue by hjsyoo** [ucsdlib/damsmanager#368]
### Descriptive summary
Note: this ticket was re-specified on 2019-10-23 to capture the discussion at the DAMS Working Group meeting on 2019-10-15.

When re-ordering DAMS elements as indicated in https://github.com/ucsdlib/damspas/issues/632, apply a conditional placement for Note:Preferred Citation.

- For RDC objects, place Note:Preferred Citation immediately before Note:Description.
- For non-RDC objects, place Note:Preferred Citation immediately before Copyright boilerplate.
- For all objects, the label should remain "Cite This Work"

### Rationale

This work is needed concurrent with re-ordering DAMS elements: https://github.com/ucsdlib/damspas/issues/632. The goal is to allow citations for RDC objects to be displayed in a different relative position than it is for non-RDC objects.

### Related work

https://github.com/ucsdlib/damspas/issues/632
https://github.com/ucsdlib/damspas/pull/720#

**Comment by gamontoya** [comment]
Hi @VivianChu. This ticket is waiting for input from @arwenhutt

**Comment by arwenhutt** [comment]
@gamontoya I think this does need DAMS metadata policy group discussion -- I'd also like to discuss with @ucsdlib/domm the property name.

**Comment by hjsyoo** [comment]
That sounds fine, although I wonder if the working group might also be appropriate? The key request here is for a way for RDC and non-RDC objects to have different rank placement for the Preferred Citation field. We aren't tied to a particular strategy for accomplishing this.

**Comment by arwenhutt** [comment]
@jessicahilt @gamontoya @hjsyoo Yeah, if the ticket is really a request for: 
> RDC and non-RDC objects to have different rank placement for the Preferred Citation field
then developer feedback / working group discussion makes sense.

The solution in this ticket is definitely workable, but there might be beter options.  
E.g. Like context specific rendering, e.g. if an object is in the rdcp unit, then display the elements in a different order.  I have no idea if that would be even doable, or whether it would be better or worse, than adding a new property to the data model and all of the damsmanager tools.  

For the new property solution, I think the main costs are:
- adding it to the data model and the damsmanager tools 
- confusion caused by having two such similar properties - though I think this could be mitigated by using a property name like "preferredCitationRDCP" that makes it more obvious when to use one vs. the other

**Comment by gamontoya** [comment]
Per Matt, `put a conditional on the code`.

**Comment by gamontoya** [comment]
@VivianChu See above. If there are issues, please discuss with Matt.

**Comment by VivianChu** [comment]
@gamontoya - It's fine to use a conditional on the code.  I just want to confirm the change.  For rdc object, the preferred citation note will be displayed as "Cite This Work" above Note:Description element. For non-rdc object, then it will be displayed as "Preferred Citation" above the Copyright element.  Is that correct?  Thanks

**Comment by hjsyoo** [comment]
@mdpeters @cgarciaspitz Do you want to keep the "Cite This Work" label on Note:Preferred Citation? I don't think we discussed changing this, so want to confirm that the label should remain as is for non-RDC objects?

**Comment by mdpeters** [comment]
@hjsyoo "Cite This Work" label is fine by me.
