### ISSUE TITLE
Batch metadata overlay fails on validated metadata, due to FAST topics

### ISSUE THREAD

**Issue by remerjohnson** [ucsdlib/damsmanager#378]
### Descriptive summary

The batch metadata overlay tool passed validation on this spreadsheet, which was to edit 10 objects in Mexican Broadsides:

[batchExport-64102016_fixes_with_MDP_MM_edits_stage1.xlsx](https://github.com/ucsdlib/damsmanager/files/3918094/batchExport-64102016_fixes_with_MDP_MM_edits_stage1.xlsx)

However, upon overlay, it reported 5 out of 10 objects had failed to be updated:

[damslog--860772700.txt](https://github.com/ucsdlib/damsmanager/files/3918132/damslog--860772700.txt)

The ARK report says that all outcomes were successful: 

[damslog--860772700-arkReport.xlsx](https://github.com/ucsdlib/damsmanager/files/3918136/damslog--860772700-arkReport.xlsx)

### Expected Behavior

A non-valid metadata sheet (due to FAST topics or other issues) should be rejected, and errors reported.

### Actual Behavior 

The metadata is validated, but fails upon batch ingest. 

### Related work

#367

**Comment by lsitu** [comment]
@remerjohnson While using source exported from Batch Export tool, currently damsmanager is treating those FAST subject headers to be valid so that you don't have to change it while re-ingest the metadata through the Batch Edit tool. However, there is a bug that failed to translate the FAST subject headers. I think we can fix it so that the metadata can be ingested successfully. Do you want to just report an error during validation for those FAST subject headers instead, or just fix the ingest failed problem?

**Comment by remerjohnson** [comment]
@lsitu That's a good question, I would probably defer to @gamontoya on whether it's better to fix the underlying bug vs. to merely report it as an error that can be planned around. 

For my situation, if I simply excluded all topics columns form my batch overlay, would that ensure the existing topics would stay, and avoid the error?

**Comment by gamontoya** [comment]
@remerjohnson @lsitu I prefer that the 🐛 bug be fixed.

**Comment by lsitu** [comment]
@gamontoya Sure. I would go with fixing it as a bug then. @remerjohnson I would say YES for your question, and you don't need to worry about the error with those headers exported but just the metadata. And damsmanager will take care of it internally so that you won't get any errors during batch overlaying.

**Comment by arwenhutt** [comment]
reopening for testing

**Comment by remerjohnson** [comment]
I've reviewed this on testing with the original data set as well as another, and both the tests and overlay were successful. So I am calling this fixed 👍

**Comment by remerjohnson** [comment]
I've now tested this on production, and it is working as exprected.
