### ISSUE TITLE
Revert the codes on damspas that apply the CC template for UI display.

### ISSUE THREAD

**Issue by jessicahilt** [ucsdlib/damsmanager#388]
### Descriptive summary
Revert the codes on damspas that apply the CC template for UI display.

### Related work

Global data cleanup to change the existing old Use Constraint(s) (dams:copyrightNote) to the new CC copyright Use Constraint(s) template for objects with a cc license #386

Update Excel Standard InputStream in DAMS Manager to use the expected CC copyright Use Constrain(s) template on object creation #387

**Comment by arwenhutt** [comment]
@VivianChu @lsitu 
The majority of the objects we looked at displayed the constraints on use values in the rdf.   

But we noted a few things which weren't as expected:

### 1.  text displayed different from value stored
This item https://librarytest.ucsd.edu/dc/object/bb3789734j is displaying a different "constraints on use" text than is in the rdf 

### 2. inconsistent display
@abbypenn93 ingested a collection of 60 objects to staging (as part of a single batch) - when she reviewed them on monday (2/18/2020) 24 of the objects did not display constraints on use in the UI.  The values for all settings are the same for all of the records, and they all have the same rights/license, etc.  When I looked at some of the same objects, the results were different but many objects still were not displaying constraints on use text.

I noticed with these, and other records we looked at during testing, had an empty copyright property in addition to the one with content, e.g.:
`<dams:copyright><dams:Copyright /></dams:copyright>`

I believe that what may be happening is:
- when the empty block is before the correct dams:copyright block in the rdf, not text is displayed in the UI
- when the correct dams:copyright block is before the empty block in the rdf, the text is displayed
and since rdf isn't ordered, the order of the rdf can change when it's served up, thus the inconsistent results.

This may primarily be a problem with the record creation process (since those empty blocks shouldn't be there) so the fix for this may be to eliminate the creation of those empty blocks on ingest, instead of changing the UI.

**Comment by lsitu** [comment]
@arwenhutt For record https://librarytest.ucsd.edu/dc/object/bb3789734j  in `1. text displayed is different than value stored`, I think it's just a SOLR updated issue and I'll re-index it so to fix it. Do you see other records still have the issue?

For `2. inconsistent display`, it looks like it's a new issue that is no related. Could you create a damsmanager ticket and attach the Excel source file that created objects with empty copyright element so that we can inspect and fix the problem? Thank you.

**Comment by lsitu** [comment]
@arwenhutt The index for object https://librarytest.ucsd.edu/dc/object/bb3789734j that you mentioned above is updated. Could you review it again? Thanks.

**Comment by arwenhutt** [comment]
@lsitu 
#1 looks good
and I'll create a new ticket for #2 

given all of that, I think we can close this ticket.

**Comment by arwenhutt** [comment]
Link to ticket for # 2 - #402

**Comment by arwenhutt** [comment]
@lsitu - @remerjohnson verified on production ✔️
